type Team {
    id: ID!
    owner: User!
	name: String!
    members: [User!]!
    channels: [Channel!]!
}

type Channel {
    id: ID!
    name: String!
    isPublic: Boolean!
	owner: User!
	team: Team!
    messages: [Message!]!
    members: [User!]!
}

type Message {
    id: ID!
    text: String!
    user: User!
	timestamp: String!
    channel: Channel!
}

type User {
	id: ID!
    username: String!
    email: String!
    teams: [Team!]!
}

type Query {
    ping: String!

	userTeamList(userId: Int!): [Team!]!
	channelMessageList(channelId: Int!): [Message!]!
	teamChannelList(teamId: Int!): [Channel!]!

	team(id: Int!): Team!
	channel(id: Int!): Channel!
	user(id: Int!): User!
}

input CreateUserInput {
	username: String!
	email: String!
	password: String
}

input SendMessageInput {
	userId: Int!
	channelId: Int!
	text: String!
}

input CreateTeamInput {}
input CreateChannelInput {}
input AddUserToTeam {}
input AddUserToChannel {}

type CreateUserOutput {
	user: User!
}

type SendMessageOutput {
	ok: Boolean!
}

type Mutation {
	createUser(input: CreateUserInput!) CreateUserOutput!
	createTeam(input: CreateTeamInput!) CreateTeamOutput!
	createChannel(input: CreateChannelInput!) CreateChannelOutput!

	addUserToTeam(input: AddUserToTeam!) AddUserToTeamOutput!
	addUserToChannel(input: AddUserToChannel!) AddUserToChannel!

	sendMessage(input: SendMessageInput!) SendMessageOutput!
}

schema {
	query: Query
}
