// DO NOT EDIT - Auto generated by sqltype for Password

package domain

import (
	"database/sql/driver"
	"fmt"
	"reflect"
)

func (t *Password) Scan(value interface{}) error {

	if value == nil {
		return nil
	}

	switch v := value.(type) {

	case []byte:
		*t = Password(string(v))

	case string:
		*t = Password(v)

	case *string:
		*t = Password(*v)

	default:
		return fmt.Errorf("%s Can't convert '%v' to string", reflect.TypeOf(t), value)
	}

	return nil
}

func (t Password) Value() (driver.Value, error) {

	return string(t), nil

}
